.TH MATAHARI-BROKERD "8" "September 2011" "matahari-brokerd"

.SH NAME
matahari-brokerd - Part of the Matahari suite of remote agents

.SH SYNOPSIS
.B matahari-brokerd
\fI<options>\fR

.SH Description

This is a wrapper around qpidd.  It processes configuration from the Matahari
broker configuration file (/etc/sysconfig/matahari-broker) and then runs qpidd.
All options acceppted by qpidd are accepted by matahari-brokerd.
