module HSA
  class Writer
    def named_conf
      tpl = %Q|//
// named.conf
//
// generated by #{$0}
//

options {
  listen-on port 53 { 127.0.0.1; };
  listen-on-v6 port 53 { ::1; };
  directory   "/var/named";
  dump-file   "/var/named/data/cache_dump.db";
        statistics-file "/var/named/data/named_stats.txt";
        memstatistics-file "/var/named/data/named_mem_stats.txt";
  allow-query     { localhost; };
  recursion yes;

  // dnssec-enable no;
  // dnssec-validation no;
  // dnssec-lookaside auto;

  /* Path to ISC DLV key */
  // bindkeys-file "/etc/named.iscdlv.key";

  // managed-keys-directory "/var/named/dynamic";
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

zone "matahariproject.org" {
  type master;
  notify no;
  allow-query { any; };
  file "matahariproject.zone";
};

zone "1.168.192.in-addr.arpa" {
  type master;
  notify no;
  allow-query { any; };
  file "192-168-1.zone";
};

view "localhost_resolver"
{
  match-clients { localhost; };
  match-destinations { localhost; };
  recursion yes;
  zone "." IN {
    type hint;
    file "named.ca";
  };

  include "/etc/named.rfc1912.zones";
  //include "/etc/named.root.key";
};
|
    end
    
    def zone address, ip
      # Write zone files with address,ip
    end
  end
end
