#!/usr/bin/env python

from matahari.interpreter.interpreter import Interpreter
from matahari.mode import RootMode

def main():
    mode = RootMode()
    shell = Interpreter('mhsh', mode)
    shell.cmdloop()

if __name__ == '__main__':
    main()
